### ISSUE TITLE
Query Regarding Intrinsic Scatter Output/Calculation in BCES

### ISSUE THREAD

**Issue by rebecabatalha** [rsnemmen/BCES#10]
Olá! /Hello maintainers/contributors,

Firstly, thank you for sharing the code. I have noticed that the code includes a feature for accounting for intrinsic scatter, which is a critical feature for my current work. Secondly, I have a specific query regarding the intrinsic scatter:

1. Does the code currently provide an output for the intrinsic scatter value and its associated uncertainty?

2. If the code doesn't directly output these values, is there a recommended way to derive them using other parameters or results given by the package?

I appreciate your dedication to this tool and your insights will be very helpful. I'm looking forward to your guidance on this matter.

Best regards,
Rebeca Batalha

**Comment by rsnemmen** [comment]
### First question

BCES currently does not print the intrinsic scatter. I think it is possible to get the intrinsic scatter, but changing the source code would be needed. 

### Second question

Getting the intrinsic scatter is not straightforward. One idea is to first estimate the raw scatter of the data about the best-fit, then subtract from this the statistical uncertainties. A quick python coding would solve this, but keep in mind this would be a rough estimate.
