### ISSUE TITLE
can this code be used when errors are asymmetric?

### ISSUE THREAD

**Issue by RuiShe** [rsnemmen/BCES#3]
As you know, astronomy data often have asymmetric errors.

**Comment by Vital-Fernandez** [comment]
I would love to know Nemmen opinion on this matter:

Could you make some kind of bootstrap? Generate  arrays of random values from the asymmetric (or symmetric)  data points. For the arrays length apply the BCES and store the results. You generate an distribution of points which will may or not be asymmetric.

If this approach is correct, for each application of the BCES should you include the original error on the random points regression or you should do the regression without the error?

What do you think?

**Comment by rsnemmen** [comment]
Thanks for the question. The method can't be used in the case of asymmetric error bars (however see the comment below). The method considers only normal PDFs, and a generalization to asymmetric distributions is not straightforward: we would need to derive the BCES estimator formulas (cf. Akritas & Bershady 1996 ApJ) assuming your PDF for asymmetric errors. 

If the error bars are not too asymmetric, what I have done is to take the uncertainty as the average of the upper and lower errors. I know that this is not rigorous, but it should not give results very distant from the real ones if the upper and lower errors are comparable. 

I am outdated regarding Bayesian regression methods, but it would be worth checking if there is a bayesian method (cf. the README of this repo for some suggestions) that handles arbitrary uncertainties in the variables. Alternatively, one could write her own regression code using emcee or pymc3 allowing to handle arbitrary PDFs for the errors. The trick in this case is how to write an appropriate likelihood function. 

I hope this helps.
