### ISSUE TITLE
Add __init__py?

### ISSUE THREAD

**Issue by hposborn** [rsnemmen/BCES#5]
I'm not sure if it was just my dodgy install, but I couldn't actually use this as a module until I created an "\_\_init\_\_.py" file in the directory with the line "from BCES.bces import *".

**Comment by rsnemmen** [comment]
Could you create a pull request with this suggestion? It would be welcomed.

Rodrigo

**Comment by rsnemmen** [comment]
I added the `__init__.py` file, so now it should work.
