### ISSUE TITLE
Installation from Pypi fails

### ISSUE THREAD

**Issue by astrobarn** [rsnemmen/BCES#6]
Trying to install from Pypi fails with a missing LICENSE:

```[semelipap@seven ~]🦑 pip install bces
Collecting bces
  Using cached https://files.pythonhosted.org/packages/a0/1e/2ac48fe352febd8924db926b34c3280252dfda936fd2b5bd12688cb6c571/bces-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ECRe_1/bces/setup.py", line 6, in <module>
        with open('LICENSE') as f:
    IOError: [Errno 2] No such file or directory: 'LICENSE'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ECRe_1/bces/
```
But istalling from git works.

I think you have to declare the files you want included in package_data in the setup from setup.py or in the MANIFEST.in

**Comment by rsnemmen** [comment]
Thanks, I will have a look.

**Comment by rsnemmen** [comment]
I now included a `MANIFEST.in`. Could you check if the pip problem now vanishes?

**Comment by antoniusf** [comment]
Hi, thanks for taking care of this. Unfortunately, it appears that I just hit upon the same issue.

It seems that PyPI is still serving the version from April 11: [https://pypi.org/project/bces/#files](https://pypi.org/project/bces/#files). Could you take a look at that?

**Comment by rsnemmen** [comment]
I think I finally took care of the issue with installations via pip. It took me a while. I had to rebuild the packages locally and upload them to the server, also being careful about updating the `setup.py` file.

Thanks for the patience.

**Comment by antoniusf** [comment]
Thanks so much for fixing this!
