### ISSUE TITLE
1. How to get the  uncertainties on the parameters derived from the fits? 2. If there is only y error, how to use the BCES package?

### ISSUE THREAD

**Issue by rylanlee** [rsnemmen/BCES#7]
So sorry that I found nothing about the two questions on the example. Thers is no introducing documents (right?) about the package.

**Comment by rylanlee** [comment]
So sorry that I found nothing about the two questions on the example. Thers is no introducing documents (right?) about the package.

**Comment by arielwrl** [comment]
A possible answer to 1 is to use prediction bands, at least that is what I do.

**Comment by rylanlee** [comment]
> A possible answer to 1 is to use prediction bands, at least that is what I do.
assum Y = aX + b,
I cheched the README.md and found that there is aerr & berr in the output, but both aerr and berr has four number as well as a & b. To 2, maybe just a zero list is OK

**Comment by rylanlee** [comment]
> A possible answer to 1 is to use prediction bands, at least that is what I do.

assum Y = aX + b,
I cheched the README.md and found that there is aerr & berr in the output, but both aerr and berr has four number as well as a & b. To 2, maybe just a zero list is OK.

Moreover, I followed the example, in Plot with fit confidence band:
# array with best-fit parameters
fitm=numpy.array([ a[i],b[i] ])	
# covariance matrix of parameter uncertainties
covm=numpy.array([ (aerr[i]**2,covab[i]), (covab[i],berr[i]**2) ])

but 'i' is not defined in the example 2,  whihc one do you defined in your use?

**Comment by rsnemmen** [comment]
Hey, I will improve the documentation with info on how to get the parameter uncertainties for beginners. More news soon.

**Comment by rsnemmen** [comment]
Dear @rylanlee, 
Sorry I left this open for so long. You can get the 1-sigma uncertainties on the regression parameters by looking at the aerr and berr (cf. section USAGE in README). 

If you have only y-errors, then BCES is not really appropriate. I suggest using weighted least squares. I plan to incorporate WLS in this package at some point in the future. 

I hope this helps.
